<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="CapaVista_Navegador">
      <HintPath>..\..\Modelo_MVC\CapaVista_Navegador\bin\Debug\CapaVista_Navegador.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>