<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Data.Odbc" Version="9.0.7" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Capa_Vista_Navegador">
      <HintPath>..\Modelo_MVC\CapaVista_Navegador\bin\Debug\Capa_Vista_Navegador.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>